deployment:
  tasks:
    - export DEPLOYPATH=/home/vene2l4cds65/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
cd ~/repositories/Shothawk-Alternative/client   # change this to your actual repo folder
git status
